version: "3.9"
   
services:
  db:
    image: postgres
    environment:
      - POSTGRES_DB=ccsovs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
    - "5432:5432"

  web:
    build: ./ccsovs
    # python manage.py collectstatic --noinput &&
    command: >
      sh -c "
             python manage.py makemigrations settings &&
             python manage.py makemigrations election &&
             python manage.py migrate &&
             python manage.py createsuperuser --noinput &&
             python manage.py runserver 0.0.0.0:8000"
    environment:
      DJANGO_SUPERUSER_PASSWORD: admin
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_EMAIL: admin@admin.com
      DB_NAME: ccsovs
      DB_USER: postgres
      DB_PASS: postgres
      DB_HOST: db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - db